# Generated by Django 3.0.3 on 2020-05-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='codertjay@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
