# Generated by Django 3.0.3 on 2020-06-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='author',
        ),
    ]
