# Generated by Django 3.0.3 on 2020-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200603_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user/profile.jpg', null=True, upload_to=''),
        ),
    ]
